version: "3"
services:
  server:
    image: 730335588602.dkr.ecr.us-east-1.amazonaws.com/bia-ecr:latest
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: bia.cbuicaeqisxy.us-east-1.rds.amazonaws.com
      DB_PORT: 5432